name: run-tests
on:
  create:
    tags:
      - "v[0-9].[0-9]+.[0-9]+"
jobs:
  test:
    uses: mdietrichstein/skpredict/.github/workflows/run-tests.yml@main
  publish-on-pypi:
    needs: test
    uses: mdietrichstein/skpredict/.github/workflows/publish-pypi.yml@main
    with:
      username: mdietrichstein
      repository: https://upload.pypi.org/legacy/
    secrets:
      password: ${{ secrets.TEST_PYPI_PASSWORD }}
