on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      repository:
        required: true
        type: string
    secrets:
      password:
        required: true

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: pip install -r dev_requirements.txt
      - run: python setup.py sdist bdist_wheel
      - run: twine upload -u "${{ inputs.username }}" -p "${{ secrets.password }}"  --repository-url ${{ inputs.repository }} dist/

