name: run-tests
on:
  create:
    tags:
      - "v[0-9].[0-9]+.[0-9]+-dev"
jobs:
  release-on-test-pypi:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo add-apt-repository -y ppa:deadsnakes/ppa
      - run: sudo apt-get update
      - run: sudo apt install -y python3.7 python3.8 python3.9 python3.10
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pip install -r dev_requirements.txt
      - run: make lint
      - run: make test-matrix
      - uses: mdietrichstein/skpredict/.github/workflows/publish-pypi.yml@main
          with:
            username: mdietrichstein
            repository: https://test.pypi.org/legacy/
          secrets:
            password: ${{ secrets.TEST_PYPI_PASSWORD }}

