name: publish-dev
on:
  push:
    tags:
      - "v[0-9]\.[0-9]+\.[0-9]+-dev"
jobs:
  test:
    uses: mdietrichstein/skpredict/.github/workflows/run-tests.yml@main
  publish-on-test-pypi:
    needs: test
    uses: mdietrichstein/skpredict/.github/workflows/publish-pypi.yml@main
    with:
      username: mdietrichstein
      repository: https://test.pypi.org/legacy/
    secrets:
      password: ${{ secrets.TEST_PYPI_PASSWORD }}
