name: publish-release
on: workflow_dispatch
jobs:
  test:
    uses: mdietrichstein/skpredict/.github/workflows/run-tests.yml@main
  publish-on-pypi:
    needs: test
    uses: mdietrichstein/skpredict/.github/workflows/publish-pypi.yml@main
    with:
      username: mdietrichstein
      repository: https://upload.pypi.org/legacy/
    secrets:
      password: ${{ secrets.PYPI_PASSWORD }}
