name: run-tests
on: [push]
jobs:
  setup:
    - run: sudo add-apt-repository -y ppa:deadsnakes/ppa
    - run: sudo apt-get update
    - run: sudo apt install -y python3.6 python3.7 python3.8 python3.9
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - run: pip install -r dev_requirements.txt
  test:
    needs: setup
    steps:
      - run: make test-matrix
