name: run-tests
on: [push]
jobs:
  test-matrix:
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get update
      - run: sudo apt install -y python3.7 python3.8 python3.9
      - uses: actions/checkout@v2
      - run: pip install -r requirements.txt
      - run: pip install -r dev_requirements.txt
      - run: make lint
      - run: make test-matrix
